/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'
import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as EditorLoginRouteImport } from './routes/editor/login'
import { Route as AppWorkRouteImport } from './routes/_app/work'
import { Route as AppContactRouteImport } from './routes/_app/contact'
import { Route as AppCompanyRouteImport } from './routes/_app/company'
import { Route as EditorAuthRouteRouteImport } from './routes/editor/_auth/route'
import { Route as AppBlogIndexRouteImport } from './routes/_app/blog/index'
import { Route as EditorAuthNewRouteImport } from './routes/editor/_auth/new'
import { Route as EditorAuthPostIdRouteImport } from './routes/editor/_auth/$postId'
import { Route as AppBlogSlugRouteImport } from './routes/_app/blog/$slug'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const EditorRouteImport = createFileRoute('/editor')()
const rootServerRouteImport = createServerRootRoute()

const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const EditorLoginRoute = EditorLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => EditorRoute,
} as any)
const AppWorkRoute = AppWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCompanyRoute = AppCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AppRouteRoute,
} as any)
const EditorAuthRouteRoute = EditorAuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => EditorRoute,
} as any)
const AppBlogIndexRoute = AppBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AppRouteRoute,
} as any)
const EditorAuthNewRoute = EditorAuthNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EditorAuthRouteRoute,
} as any)
const EditorAuthPostIdRoute = EditorAuthPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => EditorAuthRouteRoute,
} as any)
const AppBlogSlugRoute = AppBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/editor': typeof EditorAuthRouteRouteWithChildren
  '/company': typeof AppCompanyRoute
  '/contact': typeof AppContactRoute
  '/work': typeof AppWorkRoute
  '/editor/login': typeof EditorLoginRoute
  '/': typeof AppIndexRoute
  '/blog/$slug': typeof AppBlogSlugRoute
  '/editor/$postId': typeof EditorAuthPostIdRoute
  '/editor/new': typeof EditorAuthNewRoute
  '/blog': typeof AppBlogIndexRoute
}
export interface FileRoutesByTo {
  '/editor': typeof EditorAuthRouteRouteWithChildren
  '/company': typeof AppCompanyRoute
  '/contact': typeof AppContactRoute
  '/work': typeof AppWorkRoute
  '/editor/login': typeof EditorLoginRoute
  '/': typeof AppIndexRoute
  '/blog/$slug': typeof AppBlogSlugRoute
  '/editor/$postId': typeof EditorAuthPostIdRoute
  '/editor/new': typeof EditorAuthNewRoute
  '/blog': typeof AppBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/editor': typeof EditorRouteWithChildren
  '/editor/_auth': typeof EditorAuthRouteRouteWithChildren
  '/_app/company': typeof AppCompanyRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/work': typeof AppWorkRoute
  '/editor/login': typeof EditorLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/blog/$slug': typeof AppBlogSlugRoute
  '/editor/_auth/$postId': typeof EditorAuthPostIdRoute
  '/editor/_auth/new': typeof EditorAuthNewRoute
  '/_app/blog/': typeof AppBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/editor'
    | '/company'
    | '/contact'
    | '/work'
    | '/editor/login'
    | '/'
    | '/blog/$slug'
    | '/editor/$postId'
    | '/editor/new'
    | '/blog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/editor'
    | '/company'
    | '/contact'
    | '/work'
    | '/editor/login'
    | '/'
    | '/blog/$slug'
    | '/editor/$postId'
    | '/editor/new'
    | '/blog'
  id:
    | '__root__'
    | '/_app'
    | '/editor'
    | '/editor/_auth'
    | '/_app/company'
    | '/_app/contact'
    | '/_app/work'
    | '/editor/login'
    | '/_app/'
    | '/_app/blog/$slug'
    | '/editor/_auth/$postId'
    | '/editor/_auth/new'
    | '/_app/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  EditorRoute: typeof EditorRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$'
  id: '__root__' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/editor/login': {
      id: '/editor/login'
      path: '/login'
      fullPath: '/editor/login'
      preLoaderRoute: typeof EditorLoginRouteImport
      parentRoute: typeof EditorRoute
    }
    '/_app/work': {
      id: '/_app/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof AppWorkRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/company': {
      id: '/_app/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AppCompanyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/editor/_auth': {
      id: '/editor/_auth'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorAuthRouteRouteImport
      parentRoute: typeof EditorRoute
    }
    '/_app/blog/': {
      id: '/_app/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof AppBlogIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/editor/_auth/new': {
      id: '/editor/_auth/new'
      path: '/new'
      fullPath: '/editor/new'
      preLoaderRoute: typeof EditorAuthNewRouteImport
      parentRoute: typeof EditorAuthRouteRoute
    }
    '/editor/_auth/$postId': {
      id: '/editor/_auth/$postId'
      path: '/$postId'
      fullPath: '/editor/$postId'
      preLoaderRoute: typeof EditorAuthPostIdRouteImport
      parentRoute: typeof EditorAuthRouteRoute
    }
    '/_app/blog/$slug': {
      id: '/_app/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof AppBlogSlugRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppCompanyRoute: typeof AppCompanyRoute
  AppContactRoute: typeof AppContactRoute
  AppWorkRoute: typeof AppWorkRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBlogSlugRoute: typeof AppBlogSlugRoute
  AppBlogIndexRoute: typeof AppBlogIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCompanyRoute: AppCompanyRoute,
  AppContactRoute: AppContactRoute,
  AppWorkRoute: AppWorkRoute,
  AppIndexRoute: AppIndexRoute,
  AppBlogSlugRoute: AppBlogSlugRoute,
  AppBlogIndexRoute: AppBlogIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface EditorAuthRouteRouteChildren {
  EditorAuthPostIdRoute: typeof EditorAuthPostIdRoute
  EditorAuthNewRoute: typeof EditorAuthNewRoute
}

const EditorAuthRouteRouteChildren: EditorAuthRouteRouteChildren = {
  EditorAuthPostIdRoute: EditorAuthPostIdRoute,
  EditorAuthNewRoute: EditorAuthNewRoute,
}

const EditorAuthRouteRouteWithChildren = EditorAuthRouteRoute._addFileChildren(
  EditorAuthRouteRouteChildren,
)

interface EditorRouteChildren {
  EditorAuthRouteRoute: typeof EditorAuthRouteRouteWithChildren
  EditorLoginRoute: typeof EditorLoginRoute
}

const EditorRouteChildren: EditorRouteChildren = {
  EditorAuthRouteRoute: EditorAuthRouteRouteWithChildren,
  EditorLoginRoute: EditorLoginRoute,
}

const EditorRouteWithChildren =
  EditorRoute._addFileChildren(EditorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  EditorRoute: EditorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
