/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexxRouteImport } from './routes/indexx'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppWorkRouteImport } from './routes/_app/work'
import { Route as AppContactRouteImport } from './routes/_app/contact'
import { Route as AppCompanyRouteImport } from './routes/_app/company'
import { Route as AppBlogIndexRouteImport } from './routes/_app/blog/index'
import { Route as BlogBlogxSlugRouteImport } from './routes/_blog/blogx/$slug'
import { Route as AuthEditorNewRouteImport } from './routes/_auth/editor/new'
import { Route as AppBlogSlugRouteImport } from './routes/_app/blog/$slug'
import { Route as AuthEditorPublishedSlugRouteImport } from './routes/_auth/editor/published/$slug'
import { Route as AuthEditorDraftDraftIdRouteImport } from './routes/_auth/editor/draft/$draftId'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const IndexxRoute = IndexxRouteImport.update({
  id: '/indexx',
  path: '/indexx',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkRoute = AppWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCompanyRoute = AppCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBlogIndexRoute = AppBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AppRouteRoute,
} as any)
const BlogBlogxSlugRoute = BlogBlogxSlugRouteImport.update({
  id: '/_blog/blogx/$slug',
  path: '/blogx/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEditorNewRoute = AuthEditorNewRouteImport.update({
  id: '/editor/new',
  path: '/editor/new',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppBlogSlugRoute = AppBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthEditorPublishedSlugRoute = AuthEditorPublishedSlugRouteImport.update({
  id: '/editor/published/$slug',
  path: '/editor/published/$slug',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEditorDraftDraftIdRoute = AuthEditorDraftDraftIdRouteImport.update({
  id: '/editor/draft/$draftId',
  path: '/editor/draft/$draftId',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/indexx': typeof IndexxRoute
  '/company': typeof AppCompanyRoute
  '/contact': typeof AppContactRoute
  '/work': typeof AppWorkRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/blog/$slug': typeof AppBlogSlugRoute
  '/editor/new': typeof AuthEditorNewRoute
  '/blogx/$slug': typeof BlogBlogxSlugRoute
  '/blog': typeof AppBlogIndexRoute
  '/editor/draft/$draftId': typeof AuthEditorDraftDraftIdRoute
  '/editor/published/$slug': typeof AuthEditorPublishedSlugRoute
}
export interface FileRoutesByTo {
  '/indexx': typeof IndexxRoute
  '/company': typeof AppCompanyRoute
  '/contact': typeof AppContactRoute
  '/work': typeof AppWorkRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/blog/$slug': typeof AppBlogSlugRoute
  '/editor/new': typeof AuthEditorNewRoute
  '/blogx/$slug': typeof BlogBlogxSlugRoute
  '/blog': typeof AppBlogIndexRoute
  '/editor/draft/$draftId': typeof AuthEditorDraftDraftIdRoute
  '/editor/published/$slug': typeof AuthEditorPublishedSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/indexx': typeof IndexxRoute
  '/_app/company': typeof AppCompanyRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/work': typeof AppWorkRoute
  '/auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/blog/$slug': typeof AppBlogSlugRoute
  '/_auth/editor/new': typeof AuthEditorNewRoute
  '/_blog/blogx/$slug': typeof BlogBlogxSlugRoute
  '/_app/blog/': typeof AppBlogIndexRoute
  '/_auth/editor/draft/$draftId': typeof AuthEditorDraftDraftIdRoute
  '/_auth/editor/published/$slug': typeof AuthEditorPublishedSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/indexx'
    | '/company'
    | '/contact'
    | '/work'
    | '/auth/login'
    | '/'
    | '/blog/$slug'
    | '/editor/new'
    | '/blogx/$slug'
    | '/blog'
    | '/editor/draft/$draftId'
    | '/editor/published/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/indexx'
    | '/company'
    | '/contact'
    | '/work'
    | '/auth/login'
    | '/'
    | '/blog/$slug'
    | '/editor/new'
    | '/blogx/$slug'
    | '/blog'
    | '/editor/draft/$draftId'
    | '/editor/published/$slug'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/indexx'
    | '/_app/company'
    | '/_app/contact'
    | '/_app/work'
    | '/auth/login'
    | '/_app/'
    | '/_app/blog/$slug'
    | '/_auth/editor/new'
    | '/_blog/blogx/$slug'
    | '/_app/blog/'
    | '/_auth/editor/draft/$draftId'
    | '/_auth/editor/published/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  IndexxRoute: typeof IndexxRoute
  AuthLoginRoute: typeof AuthLoginRoute
  BlogBlogxSlugRoute: typeof BlogBlogxSlugRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$'
  id: '__root__' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/indexx': {
      id: '/indexx'
      path: '/indexx'
      fullPath: '/indexx'
      preLoaderRoute: typeof IndexxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/work': {
      id: '/_app/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof AppWorkRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/company': {
      id: '/_app/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AppCompanyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/blog/': {
      id: '/_app/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof AppBlogIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_blog/blogx/$slug': {
      id: '/_blog/blogx/$slug'
      path: '/blogx/$slug'
      fullPath: '/blogx/$slug'
      preLoaderRoute: typeof BlogBlogxSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/editor/new': {
      id: '/_auth/editor/new'
      path: '/editor/new'
      fullPath: '/editor/new'
      preLoaderRoute: typeof AuthEditorNewRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/blog/$slug': {
      id: '/_app/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof AppBlogSlugRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/editor/published/$slug': {
      id: '/_auth/editor/published/$slug'
      path: '/editor/published/$slug'
      fullPath: '/editor/published/$slug'
      preLoaderRoute: typeof AuthEditorPublishedSlugRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/editor/draft/$draftId': {
      id: '/_auth/editor/draft/$draftId'
      path: '/editor/draft/$draftId'
      fullPath: '/editor/draft/$draftId'
      preLoaderRoute: typeof AuthEditorDraftDraftIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppCompanyRoute: typeof AppCompanyRoute
  AppContactRoute: typeof AppContactRoute
  AppWorkRoute: typeof AppWorkRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBlogSlugRoute: typeof AppBlogSlugRoute
  AppBlogIndexRoute: typeof AppBlogIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCompanyRoute: AppCompanyRoute,
  AppContactRoute: AppContactRoute,
  AppWorkRoute: AppWorkRoute,
  AppIndexRoute: AppIndexRoute,
  AppBlogSlugRoute: AppBlogSlugRoute,
  AppBlogIndexRoute: AppBlogIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthEditorNewRoute: typeof AuthEditorNewRoute
  AuthEditorDraftDraftIdRoute: typeof AuthEditorDraftDraftIdRoute
  AuthEditorPublishedSlugRoute: typeof AuthEditorPublishedSlugRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthEditorNewRoute: AuthEditorNewRoute,
  AuthEditorDraftDraftIdRoute: AuthEditorDraftDraftIdRoute,
  AuthEditorPublishedSlugRoute: AuthEditorPublishedSlugRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  IndexxRoute: IndexxRoute,
  AuthLoginRoute: AuthLoginRoute,
  BlogBlogxSlugRoute: BlogBlogxSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
